name: PvPReward
main: PvPReward.PvPReward
version: 1.2.0 DevBuild
author: Codisimus
website: www.codisimus.com
description: Killers steal money from their victims
commands:
  pvp:
    description: Main command, type for additional help/commands